  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: Application Budget - 18.0.0-SNAPSHOT - AWS Serverless Quarkus backends
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    ParametragesNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: parametrages/function.zip
        MemorySize: 128
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /parametres/{uri+}
              Method: any

    UtilisateursNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: utilisateurs/function.zip
        MemorySize: 128
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /utilisateurs/{uri+}
              Method: any
  Outputs:
    ParametragesNativeApi:
      Description: URL for Parametrages API
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Qua/parametres'
      Export:
        Name: ParametragesNativeApi
    UtilisateursNativeApi:
      Description: URL for Utilisateurs API
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Qua/utilisateurs'
      Export:
        Name: UtilisateursNative
