name: VALIDATE - native Java25/Mandrel25 (5 modules, temporaire)

on:
  workflow_dispatch:

jobs:
  build-native-parametrages:
    name: Native parametrages (JDK25/Mandrel25)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn -N install -B --file pom.xml
      - run: mvn clean install -B -DskipTests --file communs/pom.xml
      - run: mvn install -B -P native -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-25 --file parametrages/pom.xml

  build-native-utilisateurs:
    name: Native utilisateurs (JDK25/Mandrel25)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn -N install -B --file pom.xml
      - run: mvn clean install -B -DskipTests --file communs/pom.xml
      - run: mvn install -B -P native -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-25 --file utilisateurs/pom.xml

  build-native-comptes:
    name: Native comptes (JDK25/Mandrel25)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn -N install -B --file pom.xml
      - run: mvn clean install -B -DskipTests --file communs/pom.xml
      - run: mvn install -B -P native -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-25 --file comptes/pom.xml

  build-native-operations:
    name: Native operations (JDK25/Mandrel25)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn -N install -B --file pom.xml
      - run: mvn clean install -B -DskipTests --file communs/pom.xml
      - run: mvn install -B -P native -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-25 --file operations/pom.xml
